routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/users/list', [App\Http\Controllers\UsersController::class, 'list'])->name('users.list');


Route::resource('users', App\Http\Controllers\UsersController::class)->middleware('checkAccess:admin');
Route::resource('workers', App\Http\Controllers\WorkersController::class)->middleware('checkAccess:admin,security');
Route::resource('works', App\Http\Controllers\WorksController::class)->middleware('checkAccess:admin');
Route::resource('sections', App\Http\Controllers\SectionsController::class)->middleware('checkAccess:admin');
// Route::resource('workers_logs', App\Http\Controllers\WorkersLogsController::class)->middleware('checkAccess:admin,security');
Route::post('/works/sections', [App\Http\Controllers\WorksController::class, 'sections'])->name('works.sections');

Route::get('workers_logs/export', [App\Http\Controllers\WorkersLogsController::class,'export'])->name('workers_logs.export');
Route::get('workers_logs', [App\Http\Controllers\WorkersLogsController::class,'index'])->name('workers_logs.index');
Route::post('workers_logs', [App\Http\Controllers\WorkersLogsController::class,'store'])->name('workers_logs.store');
Route::get('workers_logs/create', [App\Http\Controllers\WorkersLogsController::class,'create'])->name('workers_logs.create');
Route::get('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'show'])->name('workers_logs.show');
Route::put('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'update'])->name('workers_logs.update');
Route::delete('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'destroy'])->name('workers_logs.destroy');
Route::get('workers_logs/{worker_log}/edit', [App\Http\Controllers\WorkersLogsController::class,'edit'])->name('workers_logs.edit');

app/Models/Worker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use App\Models\Work;
use App\Models\Section;

class Worker extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'surname', 'work_id', 'section_id'
    ];


    public function work()
    {
        return $this->belongsTo(Work::class,'work_id');
    }

    public function section()
    {
        return $this->belongsTo(Section::class,'section_id');
    }
}

app/Http/Controllers/WorkersController.php
<?php

namespace App\Http\Controllers;

use App\Models\Worker;
use App\Models\Work;
use App\Models\Section;
use Illuminate\Http\Request;

class WorkersController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
  {
      $search = $request->all();
      $s = isset($search['search'])?$search['search']:'';
      $workers = Worker::where('name', 'LIKE', '%'.$s.'%');

      if(!\Auth::user()->isAdmin()) {
        if(isset(\Auth::user()->work_id)) {
          $search['work'] = \Auth::user()->work_id;
          $search['section'] = \Auth::user()->section_id;
        } else {
          $search['work'] = -1;
        }
      }

      if(isset($search['work'])) {
        $workers->where('work_id', $search['work']);
      }

      if(isset($search['section'])) {
        $workers->where('section_id', $search['section']);
      }

      $workers = $workers->paginate(15);


      return view('workers.index', compact('workers', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $works = Work::all();
      $sections = Section::all();
        return view('workers.create',compact('works', 'sections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
      'name' => 'required|min:3|max:50',
      'surname' => 'required|min:3|max:50',
      'work_id' => 'nullable|exists:works,id',
      'section_id' => 'nullable|exists:sections,id',

      ]);

     $data = $request->all();
     Worker::create($data);

     if($request->ajax()){
         exit;
     }

     return redirect()->route('workers.index')
                     ->with('success','Zapisano.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function show(Worker $worker)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function edit(Worker $worker)
    {
      $works = Work::all();
      $sections = Section::all();
        return view('workers.edit',compact('worker', 'works', 'sections'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Worker $worker)
    {
      $this->validate($request, [
      'name' => 'required|min:3|max:50',
      'surname' => 'required|min:3|max:50',
      'work_id' => 'nullable|exists:works,id',
      'section_id' => 'nullable|exists:sections,id',
      ]);

     $data = $request->all();

      $worker->update($data);

      if($request->ajax()){
          exit;
      }

      return redirect()->route('workers.index')
                      ->with('success','Zapisano');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Worker  $worker
     * @return \Illuminate\Http\Response
     */
    public function destroy(Worker $worker)
    {
      $worker->delete();

     return redirect()->route('workers.index')
                     ->with('success','Usunięto');
    }
}

resources/views/workers/create.blade.php
@extends('layouts.app')
@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Nowy pracownik</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('users.index') }}"> Wróć</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Uwaga!</strong> Wystąpiły błędy.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('workers.store') }}" method="POST">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Imię:</strong>
                <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Imię">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nazwisko:</strong>
                <input type="text" name="surname" value="{{ old('surname') }}" class="form-control" placeholder="Nazwisko">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Miejsce pracy:</strong>
                <select name="work_id">
                  <option></option>
                  @foreach($works as $work)
                      <option value="{{ $work->id }}">{{ $work->name }}</option>
                  @endforeach
                </select>
                <select name="section_id">
                  <option></option>
                  </select>
              </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </div>
    <script type="application/javascript">
    $(document).ready(function(){
      $("[name=work_id]").change(function(){
        var $sections = $("[name=section_id]");
        $sections.find('[value]').remove();
        if($(this).val()!="") {
          $.post("{{ route('works.sections') }}", {"_token": "{{ csrf_token() }}", work: $(this).val()}, function(data){

            $.each(data.sections, function(i, item) {
              var $option = $('<option/>');
              $option.attr('value', item.id);
              $option.text(item.name);
              $sections.append($option);
            });
          });
        }
      });
    });

    </script>
</form>




@endsection

resources/views/workers/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edycja danych pracownika</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('workers.index') }}"> Wróć</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Uwaga!</strong> Wystąpiły błędy.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('workers.update',$worker->id) }}" method="POST">
    @csrf
    @method('PUT')

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Imię:</strong>
                <input type="text" name="name" value="{{ $worker->name }}" class="form-control" placeholder="Imię">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nazwisko:</strong>
                <input type="text" name="surname" value="{{ $worker->surname }}" class="form-control" placeholder="Nazwisko">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Miejsce pracy:</strong>
                <select name="work_id">
                  <option></option>
                  @foreach($works as $work)
                      <option value="{{ $work->id }}"
                        @if(isset($worker->work) && $worker->work->id == $work->id) selected="selected" @endif
                        >{{ $work->name }}</option>
                  @endforeach
                </select>
                <select name="section_id">
                  <option></option>
                  @if(isset($worker->work))
                    @foreach($worker->work->sections as $section)
                        <option value="{{ $section->id }}"
                          @if(isset($worker->section) && $worker->section->id == $section->id) selected="selected" @endif
                          >{{ $section->name }}</option>
                    @endforeach
                  @endif
                  </select>
              </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </div>
    <script type="application/javascript">
    $(document).ready(function(){
      $("[name=work_id]").change(function(){
        var $sections = $("[name=section_id]");
        $sections.find('[value]').remove();
        if($(this).val()!="") {
          $.post("{{ route('works.sections') }}", {"_token": "{{ csrf_token() }}", work: $(this).val()}, function(data){

            $.each(data.sections, function(i, item) {
              var $option = $('<option/>');
              $option.attr('value', item.id);
              $option.text(item.name);
              $sections.append($option);
            });
          });
        }
      });
    });

    </script>

</form>



@endsection

resources/views/workers/index.blade.php
@extends('layouts.app')
@section('content')

<h1>Lista pracowników</h1>
@include('searcher', array('route' => 'workers.index', 'search' => $search))
<div class="row">
  <div class="col-lg-12 actions">
    <div class="form-group">
      <a class="modal-action btn btn-primary" href="{{ route('workers.create') }}">Dodaj</a>
      <a class="btn btn-primary" href="{{ route('workers_logs.export', $search) }}">Raport</a>
    </div>
  </div>
<table class="table table-bordered table-responsive-lg">
       <tr>
           <th>Imię i nazwisko</th>
           <th>Praca</th>
           <th>Akcje</th>

       </tr>
       @foreach ($workers as $worker)
           <tr>
               <td>{{ $worker->name }} {{ $worker->surname }}</td>
               <td>
                 @if(isset($worker->work))
                  {{ $worker->work->name }}
                    @if(isset($worker->section))
                    / {{ $worker->section->name }}
                    @endif
                 @endif
               </td>
               <td>
                 @if(isset($worker->work) && isset($worker->section))
                 <a class="btn btn-primary" href="{{ route('workers_logs.index',['worker'=>$worker->id]) }}">Wejścia/wyjścia</a>
                 @endif
                 <a class="modal-action btn btn-primary" href="{{ route('workers.edit',$worker->id) }}">Edytuj</a>
                 <form action="{{ route('workers.destroy',$worker->id) }}" method="POST">
                     @csrf
                     @method('DELETE')
                     <button type="submit" class="btn btn-danger">Usuń</button>
                 </form>
               </td>
           </tr>
       @endforeach
   </table>

   {!! $workers->links() !!}

   @include('dialog')

@endsection