routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
// Route::get('/users/list', [App\Http\Controllers\UsersController::class, 'list'])->name('users.list');


Route::resource('users', App\Http\Controllers\UsersController::class)->middleware('checkAccess:admin');
Route::resource('workers', App\Http\Controllers\WorkersController::class)->middleware('checkAccess:admin,security');
Route::resource('works', App\Http\Controllers\WorksController::class)->middleware('checkAccess:admin');
Route::resource('sections', App\Http\Controllers\SectionsController::class)->middleware('checkAccess:admin');
// Route::resource('workers_logs', App\Http\Controllers\WorkersLogsController::class)->middleware('checkAccess:admin,security');
Route::post('/works/sections', [App\Http\Controllers\WorksController::class, 'sections'])->name('works.sections');

Route::get('workers_logs/export', [App\Http\Controllers\WorkersLogsController::class,'export'])->name('workers_logs.export');
Route::get('workers_logs', [App\Http\Controllers\WorkersLogsController::class,'index'])->name('workers_logs.index');
Route::post('workers_logs', [App\Http\Controllers\WorkersLogsController::class,'store'])->name('workers_logs.store');
Route::get('workers_logs/create', [App\Http\Controllers\WorkersLogsController::class,'create'])->name('workers_logs.create');
Route::get('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'show'])->name('workers_logs.show');
Route::put('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'update'])->name('workers_logs.update');
Route::delete('workers_logs/{worker_log}', [App\Http\Controllers\WorkersLogsController::class,'destroy'])->name('workers_logs.destroy');
Route::get('workers_logs/{worker_log}/edit', [App\Http\Controllers\WorkersLogsController::class,'edit'])->name('workers_logs.edit');

app/Models/Work.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Work extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 
    ];



  public function sections()
   {
       return $this->hasMany(Section::class);
   }
}

app/Http/Controllers/WorksController.php
<?php

namespace App\Http\Controllers;

use App\Models\Work;
use Illuminate\Http\Request;

class WorksController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function index(Request $request)
    {
      $search = $request->all();
      $s = isset($search['search'])?$search['search']:'';
      $works = Work::where('name', 'LIKE', '%'.$s.'%')
        ->paginate(15);


      return view('works.index', compact('works', 'search'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('works.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validate($request, [
      'name' => 'required|min:3|max:50',

      ]);

     $data = $request->all();
     Work::create($data);

     if($request->ajax()){
         exit;
     }

     return redirect()->route('works.index')
                     ->with('success','Zapisano.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Work  $work
     * @return \Illuminate\Http\Response
     */
    public function show(Work $work)
    {
        //
    }

    /**
    * Display the specified resource.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */
   public function sections(Request $request)
   {
     $work = Work::find($request->work);
     $response = array(
          'status' => 'success',
          'sections' => $work->sections
      );

      return response()->json($response);
   }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Work  $work
     * @return \Illuminate\Http\Response
     */
    public function edit(Work $work)
    {
        return view('works.edit',compact('work'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Work  $work
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Work $work)
    {
      $this->validate($request, [
      'name' => 'required|min:3|max:50',

      ]);

     $data = $request->all();

      $work->update($data);

      if($request->ajax()){
          exit;
      }

      return redirect()->route('works.index')
                      ->with('success','Zapisano');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Work  $work
     * @return \Illuminate\Http\Response
     */
    public function destroy(Work $work)
    {
      $work->delete();

     return redirect()->route('works.index')
                     ->with('success','Usunięto');
    }
}

resources/views/works/create.blade.php
@extends('layouts.app')
@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Nowy zakład</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('works.index') }}"> Wróć</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Uwaga!</strong> Wystąpiły błędy.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('works.store') }}" method="POST">
    @csrf

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nazwa:</strong>
                <input type="text" name="name" value="{{ old('name') }}" class="form-control" placeholder="Nazwa">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </div>

</form>




@endsection

resources/views/works/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edycja zakładu</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('works.index') }}"> Wróć</a>
        </div>
    </div>
</div>

@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Uwaga!</strong> Wystąpiły błędy.<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

<form action="{{ route('works.update',$work->id) }}" method="POST">
    @csrf
    @method('PUT')

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Nazwa:</strong>
                <input type="text" name="name" value="{{ $work->name }}" class="form-control" placeholder="Nazwa">
            </div>
        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
          <button type="submit" class="btn btn-primary">Zapisz</button>
        </div>
    </div>


</form>



@endsection

resources/views/works/index.blade.php
@extends('layouts.app')
@section('content')

<h1>Lista zakładów</h1>
<div class="row">
  <div class="col-lg-12 actions">
    <div class="form-group">
      <a class="modal-action btn btn-primary" href="{{ route('works.create') }}">Dodaj</a>
      <a class="btn btn-primary" href="{{ route('workers_logs.export') }}">Raport</a>
    </div>
  </div>
<table class="table table-bordered table-responsive-lg">
       <tr>
           <th>Nazwa</th>
           <th>Akcje</th>

       </tr>
       @foreach ($works as $work)
           <tr>
               <td>{{ $work->name }}</td>
               <td>
                 <a class="btn btn-primary" href="{{ route('workers_logs.export', ['work'=>$work->id]) }}">Wejścia/wyjścia</a>
                 <a class="btn btn-primary" href="{{ route('sections.index',['work'=>$work->id]) }}">Działy</a>
                 <a class="modal-action btn btn-primary" href="{{ route('works.edit',$work->id) }}">Edytuj</a>

                 <form action="{{ route('works.destroy',$work->id) }}" method="POST">
                     @csrf
                     @method('DELETE')
                     <button type="submit" class="btn btn-danger">Usuń</button>
                 </form>
               </td>
           </tr>
       @endforeach
   </table>

   {!! $works->links() !!}

   @include('dialog')

@endsection